# ===========================
# SERVICES
# ===========================
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html/wordpress
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: always

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "${NGINX_PORT}:443" # host-port : port-container
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html/wordpress
    secrets:
      - db_password
    env_file:
      - .env
    restart: always

# ----------------------------------------
# Global Configuration of Networks 
# ----------------------------------------
networks:
  inception_network:
    driver: bridge

# ----------------------------------------
# Global Configuration of Volumes 
# ----------------------------------------
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

# ----------------------------------------
# Global Configuration of Secrets
# ----------------------------------------
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  wp_admin_password:
    file: secrets/wp_admin_password.txt
