# ===========================
# SERVICES
# ===========================
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html/wordpress

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "${NGINX_PORT}:443" # host-port : port-container
    #      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html/wordpress
    secrets:
      - db_password
    env_file:
      - .env
    restart: always

# ----------------------------------------
# Global Configuration of Networks 
# ----------------------------------------
networks:
  inception_network:
    driver: bridge

# ----------------------------------------
# Global Configuration of Volumes 
# ----------------------------------------
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

# ----------------------------------------
# Global Configuration of Secrets
# ----------------------------------------
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
