version: '3.8'

# ===========================
# SERVICES
# ===========================
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql

# ----------------------------------------
# Global Configuration of Secrets
# ----------------------------------------
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

# ----------------------------------------
# Global Configuration of Networks 
# ----------------------------------------
networks:
  inception_network:
    driver: bridge

# ----------------------------------------
# Global Configuration of Volumes 
# ----------------------------------------
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  # here add wordpress
